### ISSUE TITLE
Opencpop stage 8 error

### ISSUE THREAD

**Issue by jerryuhoo** [SJTMusicTeam/Muskits#130]
```
Traceback (most recent call last):
  File "/home/y/anaconda3/envs/muskit/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/y/anaconda3/envs/muskit/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "pyscripts/utils/evaluate_mcd.py", line 138, in calculate
    assert len(corresponding_list) == 1
```

gen_path is `exp/svs_train_raw_phn_none_zh/decode_valid.loss.best/test/wav/opencpop_2100003745.wav`
gt_file_list is `['wav_dump/2044001628_bits16.wav',  ... ]`

https://github.com/SJTMusicTeam/Muskits/blob/3750a54f414761bb8bd72b1f0914b442d34cb176/egs/TEMPLATE/svs1/pyscripts/utils/evaluate_mcd.py#L133-L135

gt_file_list doesn't contain "opencpop" so opencpop_2100003745 is not in the list.

**Comment by ftshijt** [comment]
@PeterGuoRuc can you check the evaluate_mcd scripts over this issue?
